{% set name = "sphinxcontrib-httpdomain" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2059cfabd0cca8fcc3455cc8ffad92f0915a7d3bb03bfddba078a6a0f35beec5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sphinx >=1.5
    - six

test:
  imports:
    - sphinxcontrib

about:
  home: https://github.com/sphinx-contrib/httpdomain
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx domain for describing HTTP APIs
  description: |
    This contrib extension, `sphinxcontrib.httpdomain¡, provides a Sphinx domain
     for describing HTTP APIs.
  doc_url: https://sphinxcontrib-httpdomain.readthedocs.io/en/stable/
  dev_url: https://github.com/sphinx-contrib/httpdomain

extra:
  recipe-maintainers:
    - carlodri
