travis:
  secure:
    BINSTAR_TOKEN: PIAMGBwESwkdeHq90Rv4iDwaUv60p9k2B/Y4y0JJTLVk1qbKlRV+6vphIdf1i751+QlHFaBhYxOqMaFyuX6IsFB+Vzkfo9KkkBz9c68lQhpIT3ASvwDuM4s+yZxFuWGi85jQvdfsZoeNfWjccQzzC/pxu69ShkQqBUfgfjxazln7Hw7VHfXex4KDSAfqftHPhw9QKqbWMMVfyUiGTjeZE7hFV89Y+gEZrvXQiFFlJbPsAdcxaVw50whZ5gzs6cYAY+IneKrxsf8QDlyx/4xDeNNMdBZuolzj/k0SjB2nsO8WB0F0szfM9z89vf0v7lf/h4gjwazpzM+qqJHyPgkKjivihBNwlE9taLikvd8c6WeY5F24nv78dMmRa5Gs2U4XbVtG37+FDh7QPTn5sqZ/slRammGz0aZ4DOPrX5fiAfCn6alqvYC1TfG8fgRdfXXlAeTuSHtZ+1+s58Hbuise/kHzKYwMmt1t5AojWKpyayALWyFoHJopiv5pB1AcyNt8nCma7xqgwdW6xCw1Jl7uzZ4P7v+EVAZ++zzu4KNSun7nvL/Nd6bgdSoNHHG3IwKt0hfqvtJevfrPDWJk/szIMa1fr2YM0i5xPpFCspl4oR15Gg1CY/ZYHnW/byRG088I1miOaluaG5OFuDYZTk8oOxpIs8DkfzVlhnnRw0nme2g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
